# Generated by Django 3.2.13 on 2022-07-03 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20220703_1041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
