# Generated by Django 3.2.13 on 2022-07-03 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a668db80-9bd9-4385-ade3-8d1d758e393e')),
        ),
    ]
