# Generated by Django 3.2.13 on 2022-07-03 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('24cf305a-f10c-460b-9ef1-9cbaae3cbbae')),
        ),
    ]
