# Generated by Django 3.2.13 on 2022-06-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(upload_to='static/avatars/%Y/%m/'),
        ),
    ]
