# Generated by Django 3.2.13 on 2022-07-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('user', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='room',
            field=models.ManyToManyField(related_name='room_members', to='room.Room'),
        ),
    ]
