# Generated by Django 3.2.13 on 2022-07-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='room',
        ),
    ]
